### ISSUE TITLE
Bring cyberspace back

### ISSUE THREAD

**Issue by adamperkowski** [ChrisTitusTech/ageoftitus#1]
@ChrisTitusTech. We loved cyberspace. You said "CYBERSCAPE FOR LIFE". You can't just abandon it like this. Bring it back.

[clip](https://www.twitch.tv/christitustech/clip/EnjoyableOilyStarlingBibleThump-rQjyo5VWQq35F1wt).

**Comment by hedho** [comment]
@adamperkowski Totally right.

**Comment by Giraffes19** [comment]
Big mistake not to bring it back

**Comment by adamperkowski** [comment]
Okay. Chris convinced, Cyberspace is back. If he ever decides to do this again, I'll reopen this issue.

**Comment by adamperkowski** [comment]
https://github.com/ChrisTitusTech/ageoftitus/pull/3#issuecomment-2418178605

**Comment by ChrisTitusTech** [comment]
Ok I added the MIT License 03a1b6cc5913f2a7f6f698cbc069b6e7e63ce384
